# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'WeatherApp2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherApp2
  pod 'Alamofire', '~> 5.0.0.beta.1'	
end
